
fragment AnimeParts on Media {
  id
  title {
    romaji
  }
  coverImage {
    extraLarge
  }
  idMal
  status
}

query UserAnimeList($username: String) {
  MediaListCollection(
    userName: $username
    type: ANIME
    sort: UPDATED_TIME_DESC
  ) {
    lists {
      entries {
        media {
          ...AnimeParts
        }
      }
    }
  }
}
