#import "./anime.gql"



query UserAnimeList($username: String) {
  MediaListCollection(
    userName: $username
    type: ANIME
    sort: UPDATED_TIME_DESC
  ) {
    lists {
      entries {
        media {
          ...AnimeParts
        }
      }
    }
  }
}
