
fragment AnimeParts on Media {
  id
  title {
    romaji
userPreferred
    native
    english

  }
  coverImage {
    extraLarge
  }
  idMal
  status
}

query Anime($id: Int) {
  Media(id: $id, type: ANIME) {
   ...AnimeParts
    characters {
      nodes {
        gender

        image {
          large
        }
        name {
          userPreferred
        }
        id
        favourites
        isFavourite
      }
    }
  }
}
